# The Compose file is a YAML file defining services, networks, and volumes for a Docker application.

version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false      # run on http://.
                                          # if true: run on https://